name: services
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  flutter_background_service_ios: ^5.0.3
  flutter_local_notifications: ^18.0.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
